/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import modelo.Hilo;

/**
 *
 * @author tecnologiamultimedia
 */
public class FRM_Ventana extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Ventana
     */
    
    Hilo hilo;
    public String estado="EnElSuelo";
    Icon iconoUno, iconoDos;
    int contador=0;
    public FRM_Ventana() {
        initComponents();
        this.setSize(350, 350);
        jl_Obstaculo.setLocation(500, 340);
        hilo=new Hilo(this);
        hilo.start();
        iconoUno=new ImageIcon(getClass().getResource("../images/uno.png"));
        iconoDos=new ImageIcon(getClass().getResource("../images/dos.png"));
    }
    public void cambiarIcono()
    {
        contador++;
        if(contador%2==0)
        {
            jl_Tiempo.setIcon(iconoUno);
        }
        else
        {
            jl_Tiempo.setIcon(iconoDos);    
        }
        
    }
    
    public void moverFondo()
    {
        if(jl_Fondo.getX()>-350)
        {
            jl_Fondo.setLocation(jl_Fondo.getX()-10, jl_Fondo.getY());
        }
        else
        {
            jl_Fondo.setLocation(0, jl_Fondo.getY());
        }
    }
    
    public void moverObstaculo()
    {
        if(jl_Obstaculo.getX()>-50)
        {
            jl_Obstaculo.setLocation(jl_Obstaculo.getX()-15, jl_Obstaculo.getY());
        }
        else
        {
            jl_Obstaculo.setLocation(400, jl_Obstaculo.getY());
        }
    }
    
    public void comprobarColision()
    {
        if(jl_Personaje.getX()+50>jl_Obstaculo.getX() && jl_Obstaculo.getX()+50>jl_Personaje.getX() && jl_Personaje.getY()+50>jl_Obstaculo.getY() )
        {
            System.out.println("Colisión");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_Personaje = new javax.swing.JLabel();
        jl_Obstaculo = new javax.swing.JLabel();
        jl_Tiempo = new javax.swing.JLabel();
        jl_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 350));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_Personaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lilo-y-Stich-01.gif"))); // NOI18N
        getContentPane().add(jl_Personaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 80, 50));

        jl_Obstaculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panda.gif"))); // NOI18N
        getContentPane().add(jl_Obstaculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 60, 50));
        getContentPane().add(jl_Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 50, 40));

        jl_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo_mario.jpeg"))); // NOI18N
        getContentPane().add(jl_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if(evt.getKeyCode()==32)
        {
            estado="Subiendo";
        }
    }//GEN-LAST:event_formKeyPressed

    public void subirPersonaje()
    {
        jl_Personaje.setLocation(jl_Personaje.getX(),jl_Personaje.getY()-20);
        
    }
    public void bajarPersonaje()
    {
        jl_Personaje.setLocation(jl_Personaje.getX(),jl_Personaje.getY()+20);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_Fondo;
    private javax.swing.JLabel jl_Obstaculo;
    public javax.swing.JLabel jl_Personaje;
    private javax.swing.JLabel jl_Tiempo;
    // End of variables declaration//GEN-END:variables
}
